//program pengurangan, perkalian, pembagian
#include <cstdlib>
#include <iostream>

using namespace std;

int main(int argc, char *argv[])
{   int a=24,b=6,c=2;    
    cout<<"nilai a = "<<a<<endl;    
    cout<<"nilai b = "<<b<<endl;    
    cout<<"nilai c = "<<c<<endl;    
    cout<<"pengurangan dari a-b-c = "<<a-b-c<<endl;
     
    cout<<"nilai a = "<<a<<endl;    
    cout<<"nilai b = "<<b<<endl;    
    cout<<"nilai c = "<<c<<endl;    
    cout<<"perkalian dari a*b*c = "<<a*b*c<<endl;
     
    cout<<"nilai a = "<<a<<endl;    
    cout<<"nilai b = "<<b<<endl;    
    cout<<"nilai c = "<<c<<endl;    
    cout<<"pembagian dari a/b/c = "<<a/b/c<<endl;     
    
	system("PAUSE");   
    return EXIT_SUCCESS;
} 

